# -*- coding: utf-8 -*-
"""word2vec_sample.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uVjEwCIN3w9Kzx1FQQYTpakgvConds2v
"""

from gensim.test.utils import common_texts
from gensim.models import Word2Vec

model = Word2Vec(sentences=common_texts, window=5, min_count=1, workers=4)
model.save("word2vec.model")

model = Word2Vec.load("word2vec.model")

vector = model.wv['computer']  # get numpy vector of a word

print(model.wv['computer'])

